/*
 *	Auszuführen mit Node.js 
 */
var fs = require("fs"); //Import tools for manipulating filesystem
var webserver = require("./webserver");

var portWebserver = 8080;
var portWebsocket = 5560;

fs.writeFile("host.js", "/*\n * This file was autogenerated by the the server.\n * Do not edit the content of this file.\n * It will be overwritten without further checking on restart.\n */\n\nvar _port = " + portWebsocket +  ";\n", function(err) {
    if(err) {
        console.log("Unable to create file containing hostinformation.");
    }
}); 

webserver.start(portWebserver);
