/*
 *	Auszuführen mit Node.js 
 */
var fs = require("fs"); //Import tools for manipulating filesystem
var webserver = require("./webserver");
var Websocket = require("./websocket");
var Client = require("./client");

var portWebserver = 8080;
var portWebsocket = 5560;

fs.writeFile("client/host.js", "/*\n * This file was autogenerated by the the server.\n * Do not edit the content of this file.\n * It will be overwritten without further checking on restart.\n */\n\nvar _port = " + portWebsocket +  ";\n", function(err) {
    if(err) {
        console.log("Unable to create file containing hostinformation.");
    }
}); 

webserver.start(portWebserver);

var WebSocketServer = require('ws').Server;
var wss = new WebSocketServer({host: '0.0.0.0',port: portWebsocket});
wss.on('connection', function(ws) {
	new Client(new Websocket(ws));
	//We got a new connection
});
