/*
 * Imports 
 */
var WebSocketServer = require('ws').Server;
var fs = require("fs"); //Import tools for manipulating filesystem

/*
 * Code
 */
 
module.exports = {
	start : function(port, server) {
		fs.writeFile("client/host.js", "/*\n * This file was autogenerated by the the server.\n * Do not edit the content of this file.\n * It will be overwritten without further checking on restart.\n */\n\nvar _port = " + port +  ";\n", function(err) {
			if(err) {
				console.log("Unable to create file containing hostinformation.");
			}
		}); 
		var wss = new WebSocketServer({host: '0.0.0.0',port: port});
		wss.on('connection', function(ws) {
			server.newClient(new Websocket(ws));
		});
	}
};
